const lessonsConfig = [
    { title: "مقدمه و نصب پایتون", file: "lesson-01-intro-install.html" },
    { title: "چاپ کردن با print", file: "lesson-02-print.html" },
    { title: "متغیرها", file: "lesson-03-variables.html" },
    { title: "انواع داده", file: "lesson-04-data-types.html" },
    { title: "ورودی گرفتن از کاربر", file: "lesson-05-input.html" },
    { title: "عملگرها", file: "lesson-06-operators.html" },
    { title: "شرط if", file: "lesson-07-if.html" },
    { title: "شرط‌های چندگانه (elif/else)", file: "lesson-08-elif-else.html" },
    { title: "حلقه while", file: "lesson-09-while-loop.html" },
    { title: "حلقه for", file: "lesson-10-for-loop.html" },
    { title: "لیست‌ها", file: "lesson-11-lists.html" },
    { title: "متدهای لیست", file: "lesson-12-list-methods.html" },
    { title: "تاپل‌ها", file: "lesson-13-tuples.html" },
    { title: "دیکشنری‌ها", file: "lesson-14-dictionaries.html" },
    { title: "مجموعه‌ها", file: "lesson-15-sets.html" },
    { title: "توابع", file: "lesson-16-functions.html" },
    { title: "پارامترها و مقدار برگشتی", file: "lesson-17-parameters.html" },
    { title: "آرگومان‌های پیش‌فرض", file: "lesson-18-default-args.html" },
    { title: "توابع لامبدا", file: "lesson-19-lambda.html" },
    { title: "ماژول‌ها و import", file: "lesson-20-modules.html" },
    { title: "کار با فایل‌ها", file: "lesson-21-file-io.html" },
    { title: "مدیریت خطا", file: "lesson-22-exceptions.html" },
    { title: "لیست‌های فشرده", file: "lesson-23-list-comprehension.html" },
    { title: "ژنراتورها", file: "lesson-24-generators.html" },
    { title: "دکوریتورها", file: "lesson-25-decorators.html" },
    { title: "کلاس و شی", file: "lesson-26-classes.html" },
    { title: "متدهای خاص", file: "lesson-27-special-methods.html" },
    { title: "وراثت", file: "lesson-28-inheritance.html" },
    { title: "چندریختی", file: "lesson-29-polymorphism.html" },
    { title: "متدهای کلاس و استاتیک", file: "lesson-30-class-methods.html" },
    { title: "پروپرتی‌ها", file: "lesson-31-properties.html" },
    { title: "پروژه‌ی کتابخانه", file: "lesson-32-library-project.html" },
    { title: "ماژول‌های استاندارد", file: "lesson-33-standard-modules.html" },
    { title: "کار با JSON و CSV", file: "lesson-34-json-csv.html" },
    { title: "عبارت‌های منظم (Regex)", file: "lesson-35-regex.html" },
    { title: "تایپ‌هینت‌ها", file: "lesson-36-type-hints.html" },
    { title: "کار با SQLite", file: "lesson-37-sqlite.html" },
    { title: "تست‌نویسی", file: "lesson-38-unittest.html" },
    { title: "محیط مجازی و pip", file: "lesson-39-venv-pip.html" },
    { title: "پروژه‌ی نهایی", file: "lesson-40-final-project.html" },
    { title: "NumPy - محاسبات عددی", file: "lesson-41-numpy.html" },
    { title: "Pandas - تحلیل داده", file: "lesson-42-pandas.html" },
    { title: "Matplotlib - مصورسازی داده", file: "lesson-43-matplotlib.html" },
    { title: "Requests - کار با اینترنت", file: "lesson-44-requests.html" },
    { title: "BeautifulSoup - اسکرپینگ وب", file: "lesson-45-beautifulsoup.html" },
];